name: Build LenaNW Log Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Build with Maven
      run: mvn clean package
    
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: LenaNW-Log-1.0.0.jar
        path: target/LenaNW-Log-1.0.0.jar
        retention-days: 30
